# Generated by Django 3.0.5 on 2021-01-26 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, unique=True)),
                ('client_info', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Client1',
                'verbose_name_plural': 'Client1',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500, unique=True)),
                ('product_size', models.CharField(max_length=100)),
                ('product_weight', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Product1',
                'verbose_name_plural': 'Product1',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.IntegerField(blank=True, default=0, null=True)),
                ('order_pcs', models.IntegerField(blank=True, null=True)),
                ('order_done_pcs', models.IntegerField(blank=True, null=True)),
                ('order_palet', models.CharField(blank=True, choices=[('EPAL', 'EPAL'), ('Castom', 'Castom'), ('Other', 'Other')], max_length=50, null=True)),
                ('order_add_date', models.DateField(auto_now_add=True)),
                ('order_end_date', models.DateField()),
                ('order_in_work', models.BooleanField(default=False)),
                ('order_description', models.TextField(max_length=5200)),
                ('order_client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Client')),
                ('order_product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Product')),
            ],
            options={
                'verbose_name': 'Order1',
                'verbose_name_plural': 'Order1',
            },
        ),
    ]
