# Generated by Django 3.0.5 on 2021-02-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20210130_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_order_code', models.CharField(max_length=500, unique=True)),
                ('check_photo_name', models.CharField(max_length=100)),
                ('check_photo_date', models.DateField(auto_now_add=True)),
                ('check_validation', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Checking of picking',
                'verbose_name_plural': 'Checking of picking',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=500, unique=True)),
                ('photo_order_code', models.CharField(max_length=100)),
                ('photo_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photo',
            },
        ),
    ]
